"""Onshape integration over its REST API.

What it does: creates a document (or uses one you name), uploads the STEP files RL CAD exported and asks Onshape to
translate them, so the aircraft appears as a Part Studio / Assembly you can edit in the browser.

Credentials: create API keys at https://dev-portal.onshape.com (API keys) and set
    ONSHAPE_ACCESS_KEY, ONSHAPE_SECRET_KEY        (and ONSHAPE_BASE_URL for an enterprise stack)
Onshape accepts API keys with HTTP Basic auth.

Status: written against the documented v10 endpoints (documents, blobelements upload with translate=true,
translations); not yet exercised against a live account from this repository — run `rlcad onshape-test` first.
"""
from __future__ import annotations

import os
import time
from typing import Dict, List, Optional

API = "/api/v10"


class OnshapeError(RuntimeError):
    pass


class Client:
    def __init__(self, access: Optional[str] = None, secret: Optional[str] = None, base: Optional[str] = None):
        self.access = access or os.environ.get("ONSHAPE_ACCESS_KEY", "")
        self.secret = secret or os.environ.get("ONSHAPE_SECRET_KEY", "")
        self.base = (base or os.environ.get("ONSHAPE_BASE_URL") or "https://cad.onshape.com").rstrip("/")
        if not (self.access and self.secret):
            raise OnshapeError("Set ONSHAPE_ACCESS_KEY and ONSHAPE_SECRET_KEY (Onshape developer portal → API keys)")

    def _req(self, method, path, **kw):
        import requests
        r = requests.request(method, self.base + path, auth=(self.access, self.secret),
                             headers={"Accept": "application/json;charset=UTF-8; qs=0.09", **kw.pop("headers", {})},
                             timeout=120, **kw)
        if r.status_code >= 400:
            raise OnshapeError(f"{method} {path} → {r.status_code}: {r.text[:400]}")
        return r.json() if r.content else {}

    # ---------------------------------------------------------------- calls
    def whoami(self) -> Dict:
        return self._req("GET", f"{API}/users/sessioninfo")

    def create_document(self, name: str, description: str = "") -> Dict:
        d = self._req("POST", f"{API}/documents", json={"name": name, "description": description, "isPublic": False})
        return {"did": d["id"], "wid": d["defaultWorkspace"]["id"], "url": f"{self.base}/documents/{d['id']}"}

    def upload_and_translate(self, did: str, wid: str, path: str, flatten: bool = False) -> Dict:
        with open(path, "rb") as f:
            files = {"file": (os.path.basename(path), f, "application/octet-stream")}
            data = {"translate": "true", "flattenAssemblies": str(flatten).lower(), "yAxisIsUp": "false",
                    "encodedFilename": os.path.basename(path), "allowFaultyParts": "true"}
            return self._req("POST", f"{API}/blobelements/d/{did}/w/{wid}", files=files, data=data)

    def wait_translation(self, tid: str, timeout_s: float = 300) -> Dict:
        t0 = time.time()
        while time.time() - t0 < timeout_s:
            st = self._req("GET", f"{API}/translations/{tid}")
            if st.get("requestState") in ("DONE", "FAILED"):
                return st
            time.sleep(3)
        raise OnshapeError(f"translation {tid} still running after {timeout_s:.0f} s")


def upload_design(folder: str, name: str, parts: bool = True, client: Optional[Client] = None) -> Dict:
    """Upload out/assembly.step (and optionally each out/parts/*.step) into a new Onshape document."""
    c = client or Client()
    out = os.path.join(folder, "out")
    files: List[str] = [os.path.join(out, "assembly.step")]
    if parts:
        pd = os.path.join(out, "parts")
        files += sorted(os.path.join(pd, f) for f in os.listdir(pd) if f.endswith(".step")) if os.path.isdir(pd) else []
    missing = [f for f in files if not os.path.exists(f)]
    if missing:
        raise OnshapeError(f"export first; missing {missing[:3]}")
    doc = c.create_document(name, "Generated by RL CAD")
    results = []
    for f in files:
        up = c.upload_and_translate(doc["did"], doc["wid"], f)
        tid = up.get("translationId") or up.get("id")
        st = c.wait_translation(tid) if up.get("translationId") else up
        results.append({"file": os.path.basename(f), "state": st.get("requestState", "uploaded"),
                        "elements": st.get("resultElementIds"), "failure": st.get("failureReason")})
    return {"document": doc, "uploads": results}
